### ISSUE TITLE
escanear redes visibles por la incubadora  y configurar un wifi nuevo 

### ISSUE THREAD

**Issue by javierbrk** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#110]
En algún momento tuvimos un endpoint de scan ... ya no esta.
Esa parte es vital para poder configurara la incubadora. 
@JereC4str0  es necesario volver a agregar ese endpoint. 
@AnnieScigliano la vista esta disponible y creo que estaba funcionando no ?

**Comment by JereC4str0** [comment]
lo sacrificamos juntos, fue cuando no nos quedaban mas endpoints dinamicos

**Comment by javierbrk** [comment]
esa funcionalidad es indispensable para que el usuarie pueda conectar la incu !

**Comment by JereC4str0** [comment]
#115
