### ISSUE TITLE
la app deberia conectarse a la ip fija de la incu 

### ISSUE THREAD

**Issue by javierbrk** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#112]
Esta issue es solo para asegurarnos de que esto ya es asi. 

La persona llega con su teléfono se acerca a la incu, se conecta al wifi incu_nombre. El ip del esp es un ip fijo. Ese deberia ser el que este por defecto en la app para conectarse a la incu.

**Comment by JereC4str0** [comment]
la ip fija es 192.168.16.10
