### ISSUE TITLE
nombre de la incubadora demasiado largo

### ISSUE THREAD

**Issue by javierbrk** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#124]
Esta pull introdujo un error el nombre de la incubadora quedo muy largo y no permite cambiar las configuraciones. no funciona el método config post

https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/pull/113

la incubadora no debería tener un nombre que no pueda recibir. 

CORRER LAS PRUEBAS UNITARIAS ANTES DE HACER PULL Y ANTES DE APROBARLOS

**Comment by JereC4str0** [comment]
#129

**Comment by JereC4str0** [comment]
#147
