### ISSUE TITLE
Problema al cargar tiempo de bandejas

### ISSUE THREAD

**Issue by JereC4str0** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#148]
en la funcion set_incubator_period falta un simbolo  igual, la idea era acomodarlo al formato epoch pero solo aceptaria 9 caracteres
cuando intenté setear 1234567890 como tiempo de bandejas en las pruebas unitarias esto devolvio "error setting incubation_period"

esta es la [linea](https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/blob/284fb6cefef7873510b75ba8a1400946046ee40c/src/embedded/app/incubator.lua#L389)

**Comment by javierbrk** [comment]
en que unidades debería ingresarse el período ? en segundos ?

¿ cuanto es el período máximo ? ... un año

en caso de que sea segundos y el tiempo máximo de incubación sea un año ...

365d24h3600s = 31536000 s ... para un año serían 8 caracteres

creo que no es un problema ...
