### ISSUE TITLE
wifi not conecting

### ISSUE THREAD

**Issue by javierbrk** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#151]
Al utilziar el firmware de la rama principal  @Santiagocetran  no pudo conectar el esp a su red...  necesita asistencia, @JereC4str0  podes ayudar con esto ? 
Coordinen una reunión para destrabar esta situación @Santiagocetran @JereC4str0

**Comment by JereC4str0** [comment]
#155 intento solucionar esto en esta PR

**Comment by JereC4str0** [comment]
A.M.A
