### ISSUE TITLE
Mejorar Humedad en prototipo 1.0

### ISSUE THREAD

**Issue by fabriciopetiso** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#5]
Llevarlo a mas del 60% cambiando la fuentes de agua

**Comment by Pablomonte** [comment]
Sin fuente de humedad la incubadora se mantuvo funcionando cerca del 27% de humedad.
Al incorporar 2 humidificadores se alcanzó un 37% de humedad.
La experiencia pendiente consiste en agregar otro humidificador y estimar si el incremento de humedad sería lineal o hay otras variables. Además de estudiar el comportamiento y robustez de los elementos humidificadores en tanto funcionen 24/7

**Comment by fabriciopetiso** [comment]
![Image](https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/assets/149073085/f984c5e7-6802-4378-8ee8-c4df55767243)


Estamos  cerca, se puede agrandar la bandeja unos 5 cm de lado, y bastante de profundidad.



![Image](https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/assets/149073085/872254aa-7a7e-4091-afe7-1a92daef6cad)

**Comment by Pablomonte** [comment]
el prototipo 1.0 fué 
;)
