### ISSUE TITLE
verificar el tema de la memoria con los envios de logs en grafana 

### ISSUE THREAD

**Issue by javierbrk** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#72]
En las pruebas con la incubadora de fabri el sistema explotó porque se quedaba sin memoria cuando mandaba muchos mensajes... verificar si esto sigue siendo asi ...

**Comment by javierbrk** [comment]
Probar que esto se repita, intentar  minizar la cantidad de mensajes para ver si eso resuelve el problema .. .

**Comment by javierbrk** [comment]
pensar en una estrategia de enviar solo cosas importanes

**Comment by JereC4str0** [comment]
estoy depurando esto y encontré algo nuevo :

```[0;31mE (69541) HTTP_CLIENT: Connection failed, sock < 0[0m
[0;33mW (69671) http: esp_http_client_perform returned error 28674[0m
[0;33mW (69681) http: esp_http_client_perform returned error 28674[0m
[0;33mW (69681) http: esp_http_client_perform returned error 28674[0m
[0;33mW (69681) http: esp_http_client_perform returned error 28674[0m
[0;33mW (69691) http: esp_http_client_perform returned error 28674[0m
[0;33mW (69701) http: esp_http_client_perform returned error 28674[0m
[0;33mW (69701) http: esp_http_client_perform returned error 28674[0m
cannot create rtos task
stack traceback:
	[C]: ?
	[C]: in function 'post'
	SendToGrafana.lua:91: in function <SendToGrafana.lua:82>
error de loggg -28674
error de loggg -28674
error de loggg -28674
error de loggg -28674
error de loggg -28674
error de loggg -28674
error de loggg -28674

```

**Comment by JereC4str0** [comment]
entiendo que es por falta de memoria, pero antes decia ```out of memory``, cambie el tiempo de envio y sigue haciendo lo mismo

**Comment by JereC4str0** [comment]
> pensar en una estrategia de enviar solo cosas importanes

se me ocurre que podríamos guardar los logs en local y despues enviar a grafana lo importante , también podría comparar la memoria que usa para enviar los datos con la que usa para escribir un archivo que se borre cada x cantidad de buffer
