### ISSUE TITLE
Reemplazar las resistencias y ventiladores por otros componentes de menor demanda energética.

### ISSUE THREAD

**Issue by fabriciopetiso** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#8]
En base a lo propuesto por Río IV

**Comment by Pablomonte** [comment]
Reemplazamos las resistencias de 2 ohms de continua por una resistencia calefactor para incubadora de 200W 220v.
Hasta ahora los resultados son aceptables, no genera "tostados" en las paredes ni piso de la incu y alcanza sin problemas la temperatura de régimen.
