### ISSUE TITLE
Reemplazar la bandeja de agua por un humidificador

### ISSUE THREAD

**Issue by fabriciopetiso** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#9]
Validar en un cruce con río IV

Ojo, acá hace falta desarrollo de soft

**Comment by Pablomonte** [comment]
también implica agregar un inductor en la placa de control para exitar la membrana del humidificador

**Comment by Pablomonte** [comment]
Reemplazamos el humidificador de membrana por un microaspersor alimentado por una bomba de nafta genérica y un sistema de provisión permanente de agua.
