### ISSUE TITLE
Sistem reboots when sensor is broken

### ISSUE THREAD

**Issue by javierbrk** [AlterMundi-MonitoreoyControl/Proyecto-Incubadora#91]
Using a bme that is probably broken (wrong vcc gnd connection) 
the system simply reboots and only shows the initialization of the credentials... the failure manifests in the start_bme funcion from incubator.lua

**Comment by Pablomonte** [comment]
load_values() queda esperando la inicialización del sensor y se reinicia la esp

**Comment by javierbrk** [comment]
como se puede simular esta falla ? en el casode que el sensor no este conectado, no hay problema. El problema debe ser en alguna forma específica de conección del sensor. @Pablomonte

**Comment by javierbrk** [comment]
se podria depurar el bme280 para ver hasta donde llega poniendo prints en el archivo en la funcion init

**Comment by Pablomonte** [comment]
> como se puede simular esta falla ? en el casode que el sensor no este conectado, no hay problema. El problema debe ser en alguna forma específica de conección del sensor. @Pablomonte
Se
